version: "2"
run:
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
  timeout: 2m
  relative-path-mode: gomod

formatters:
  enable:
    - gofmt
    - goimports
  settings:    
    goimports:
      local-prefixes: 
        - github.com/byatesrae/
      
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - gocritic
    - tagliatelle
    - noctx
    - misspell
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
